# Generated by Django 5.0.6 on 2024-06-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=100)),
                ('Tel', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('DomaineActivite', models.CharField(max_length=100)),
                ('AnneeExperience', models.IntegerField()),
                ('Ville', models.CharField(max_length=70)),
                ('MotDePasse', models.CharField(max_length=50)),
            ],
        ),
    ]
