# Generated by Django 5.0.6 on 2024-07-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtisanFinder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artisan',
            old_name='localisation_geographique',
            new_name='localisation_atelier',
        ),
        migrations.RenameField(
            model_name='artisan',
            old_name='photo_profil',
            new_name='photo_de_profil',
        ),
        migrations.RenameField(
            model_name='artisan',
            old_name='ville_commune',
            new_name='ville_ou_commune',
        ),
    ]
