# Generated by Django 5.0.6 on 2024-07-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtisanFinder', '0002_rename_localisation_geographique_artisan_localisation_atelier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='metier',
            new_name='domaine_activite',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='telephone',
            new_name='numero_telephone',
        ),
        migrations.AddField(
            model_name='user',
            name='confirmer_le_mot_de_passe',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mot_de_passe',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliophoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_photos/'),
        ),
    ]
