# Generated by Django 5.0.6 on 2024-07-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtisanFinder', '0004_inscriptionclient_confirmer_le_mot_de_passe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artisan',
            old_name='numero_telephone',
            new_name='numero_de_telephone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='numero_telephone',
            new_name='numero_de_telephone',
        ),
    ]
